//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Localization.WebSiteViewItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebSiteViewItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebSiteViewItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warehouse.Localization.WebSiteViewItems.WebSiteViewItems", typeof(WebSiteViewItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitenize Trafik Kazandırır.
        /// </summary>
        public static string Bringstraffictoyourwebsite {
            get {
                return ResourceManager.GetString("Bringstraffictoyourwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Çalışmaları.
        /// </summary>
        public static string CaseStudies {
            get {
                return ResourceManager.GetString("CaseStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Ulaşın.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string Corporate {
            get {
                return ResourceManager.GetString("Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sık Sorulan Sorular.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkler.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misyon.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Servisler.
        /// </summary>
        public static string NewServices {
            get {
                return ResourceManager.GetString("NewServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAYFA BULUNAMADI.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloğumuzdan.
        /// </summary>
        public static string OurBlog {
            get {
                return ResourceManager.GetString("OurBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum.
        /// </summary>
        public static string OurLocation {
            get {
                return ResourceManager.GetString("OurLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        public static string Ourservices {
            get {
                return ResourceManager.GetString("Ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populer Kategoriler.
        /// </summary>
        public static string PopularCategories {
            get {
                return ResourceManager.GetString("PopularCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellikler.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Açıklaması.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha fazla.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Teklifi Al.
        /// </summary>
        public static string RequestQuote {
            get {
                return ResourceManager.GetString("RequestQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisler.
        /// </summary>
        public static string ServiceList {
            get {
                return ResourceManager.GetString("ServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzer Servisler.
        /// </summary>
        public static string SimilarServices {
            get {
                return ResourceManager.GetString("SimilarServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Numarası.
        /// </summary>
        public static string VatRate {
            get {
                return ResourceManager.GetString("VatRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyon.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
    }
}
