//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string Subject { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    }
}
