//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long LanguageId { get; set; }
        public string Link { get; set; }
        public Nullable<long> CategoryId { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual FAQCategories FAQCategories { get; set; }
    }
}
