//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.ProductTransactionGroup = new HashSet<ProductTransactionGroup>();
        }
    
        public long Id { get; set; }
        public string SenderName { get; set; }
        public string SenderMail { get; set; }
        public string SenderPhone { get; set; }
        public string SenderIdentityNumber { get; set; }
        public string RecipientName { get; set; }
        public string RecipientAddress { get; set; }
        public string RecipientCity { get; set; }
        public Nullable<long> RecipientCountryId { get; set; }
        public string RecipientZipCode { get; set; }
        public string RecipientPhone { get; set; }
        public string RecipientIdentityNumber { get; set; }
        public string RecipientMail { get; set; }
        public Nullable<long> ProductCurrencyUnitId { get; set; }
        public string ProductOrderDescription { get; set; }
        public Nullable<long> CargoServiceTypeId { get; set; }
        public Nullable<int> PackageCount { get; set; }
        public Nullable<long> PackageWeight { get; set; }
        public Nullable<long> PackageHeight { get; set; }
        public Nullable<long> PackageLength { get; set; }
        public Nullable<long> PackageWidth { get; set; }
        public Nullable<long> LanguageId { get; set; }
    
        public virtual CargoServiceTypes CargoServiceTypes { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual CurrencyUnits CurrencyUnits { get; set; }
        public virtual ICollection<ProductTransactionGroup> ProductTransactionGroup { get; set; }
        public virtual Languages Languages { get; set; }
    }
}
