//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packages()
        {
            this.PackagedProductGroups = new HashSet<PackagedProductGroups>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Height { get; set; }
        public Nullable<long> Width { get; set; }
        public Nullable<long> Weight { get; set; }
        public Nullable<long> Length { get; set; }
        public Nullable<int> Count { get; set; }
        public decimal Desi { get; set; }
        public Nullable<long> OrderId { get; set; }
    
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackagedProductGroups> PackagedProductGroups { get; set; }
    }
}
