//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAnswers
    {
        public long Id { get; set; }
        public Nullable<long> TicketId { get; set; }
        public string AnsweringPerson { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public bool isShow { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
